# Generated by Django 5.1.4 on 2024-12-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycloud", "0002_file_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_links",
                        to="mycloud.file",
                    ),
                ),
            ],
        ),
    ]
