# Generated by Django 5.1.4 on 2025-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycloud", "0005_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="last_downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
